name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - visualizer/*

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need tags and commit history to get changes
      - name: Get changes since last release
        id: changes
        uses: simbo/changes-since-last-release-action@v1
      - name: Output changes since last release
        run: |
          echo "Changes since ${{ steps.changes.outputs.last-tag }}:"
          echo "${{ steps.changes.outputs.log }}"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Show Python version
        run: python --version
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('visualizer/requirements.txt')}}
      - name: Install Python dependencies
        run: pip install --upgrade --upgrade-strategy eager -r visualizer/requirements.txt
      - name: Run script to deploy/remove dashboards
        env:
          HOGEFUGA: this is set to HOGEFUGA environment variable
        run: python visualizer/deploy.py
