name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - visualizer/*

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.5
        with:
          files: visualizer/.*\.json$
      - name: deploy all
        working-directory: ./visualizer
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          FILES=$(ls)
          for v in $FILES
          do
            echo $v
          done
      - name: update/create modified ones
        working-directory: ./visualizer
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for FILEPATH in ${{ steps.changed-files.outputs.all_modified_files }}
          do
            FILE=$(echo $FILEPATH | sed 's/^visualizer\///')
            echo "$FILE was modified"
          done
      - name: delete deleted ones
        working-directory: ./visualizer
        if: steps.changed-files.outputs.any_deleted == 'true'
        run: |
          for FILEPATH in ${{ steps.changed-files.outputs.deleted_files }}
          do
            FILE=$(echo $FILEPATH | sed 's/^visualizer\///')
            echo "$FILE was deleted"
          done
